# Generated by Django 2.2.4 on 2021-05-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
